name: flutter_navigation_packages
description: A Flutter project used a sandbox to test navigation packages
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  beamer: ^1.3.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  go_router: ^3.0.1
  provider: ^6.0.2
  routemaster: ^0.9.5

dev_dependencies:
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - fixtures/
